// gen_mcptools reads a schema YAML file and generates MCP tool registration
// code for each command group, writing the output to the specified Go file.
//
// Usage: go run scripts/gen_mcptools/main.go <schema.yaml> <output.go>
//
// The generated file defines a ToolGroup variable containing all operations
// from the schema, grouped as a single MCP tool. The tool uses CRUD-combined
// design: one tool per resource group with an "operation" parameter.
//
// This script is run in CI whenever the schema changes.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"

	"github.com/FabianSchurig/bitbucket-cli/scripts/internal/spec"
)

// ─── Template data types ──────────────────────────────────────────────────────

type MCPToolData struct {
	SchemaPath  string
	ToolVarName string // e.g., "PRToolGroup"
	ToolName    string // e.g., "bitbucket_pr"
	Description string // MCP tool description
	Operations  []MCPOpData
}

type MCPOpData struct {
	OperationID string
	Method      string
	Path        string
	Summary     string
	Description string
	Params      []MCPParamData
	BodyFields  []MCPBodyFieldData
	HasBody     bool
	Paginated   bool
}

type MCPParamData struct {
	Name     string
	In       string
	Type     string
	Required bool
}

type MCPBodyFieldData struct {
	Path string
	Type string
	Desc string
}

// ─── Template ─────────────────────────────────────────────────────────────────

const fileTemplate = `// Code generated by scripts/gen_mcptools/main.go DO NOT EDIT.
// Source: {{.SchemaPath}}
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_mcptools/main.go {{.SchemaPath}} <output.go>

package mcptools

// {{.ToolVarName}} contains the MCP tool definition for the "{{.ToolName}}" tool group.
var {{.ToolVarName}} = ToolGroup{
	Name:        {{goStringLit .ToolName}},
	Description: {{goStringLit .Description}},
	Operations: []OperationDef{
{{- range .Operations}}
		{
			OperationID: {{goStringLit .OperationID}},
			Method:      {{goStringLit .Method}},
			Path:        {{goStringLit .Path}},
			Summary:     {{goStringLit .Summary}},
			Description: {{goStringLit .Description}},
			Params: []ParamDef{
{{- range .Params}}
				{Name: {{goStringLit .Name}}, In: {{goStringLit .In}}, Type: {{goStringLit .Type}}, Required: {{.Required}}},
{{- end}}
			},
			BodyFields: []BodyFieldDef{
{{- range .BodyFields}}
				{Path: {{goStringLit .Path}}, Type: {{goStringLit .Type}}, Desc: {{goStringLit .Desc}}},
{{- end}}
			},
			HasBody:   {{.HasBody}},
			Paginated: {{.Paginated}},
		},
{{- end}}
	},
}
`

// ─── Template functions ───────────────────────────────────────────────────────

var templateFuncMap = template.FuncMap{
	"goStringLit": spec.GoStringLit,
}

// ─── Conversion ───────────────────────────────────────────────────────────────

func operationToMCPOp(op spec.OperationDef) MCPOpData {
	params := make([]MCPParamData, 0, len(op.Params))
	for _, p := range op.Params {
		params = append(params, MCPParamData{
			Name:     p.Name,
			In:       p.In,
			Type:     p.Type,
			Required: p.Required,
		})
	}

	flatFields := spec.FlattenBodyFields(op.BodyFields)
	bodyFields := make([]MCPBodyFieldData, 0, len(flatFields))
	for _, bf := range flatFields {
		bodyFields = append(bodyFields, MCPBodyFieldData{
			Path: bf.Path,
			Type: bf.GoType,
			Desc: bf.Desc,
		})
	}

	return MCPOpData{
		OperationID: op.OperationID,
		Method:      op.Method,
		Path:        op.Path,
		Summary:     op.Summary,
		Description: op.Description,
		Params:      params,
		BodyFields:  bodyFields,
		HasBody:     op.HasBody,
		Paginated:   op.Paginated,
	}
}

func buildToolDescription(cmdShort string, operations []MCPOpData) string {
	// Estimate ~60 chars per operation line.
	var sb strings.Builder
	sb.Grow(len(cmdShort) + 30 + len(operations)*60)
	sb.WriteString(cmdShort)
	sb.WriteString("\n\nAvailable operations:\n")
	for _, op := range operations {
		desc := op.Summary
		if desc == "" {
			desc = op.OperationID
		}
		fmt.Fprintf(&sb, "- %s: %s [%s]\n", op.OperationID, desc, op.Method)
	}
	return sb.String()
}

// ─── Main ─────────────────────────────────────────────────────────────────────

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <schema.yaml> <output.go>\n", os.Args[0])
		os.Exit(1)
	}

	schemaPath := os.Args[1]
	outputPath := os.Args[2]

	schema, err := spec.LoadSchema(schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	cmdName, cmdUse, cmdShort, _ := spec.CommandMeta(schema.Info)

	operations := spec.BuildOperations(schema)
	mcpOps := make([]MCPOpData, 0, len(operations))
	for _, op := range operations {
		mcpOps = append(mcpOps, operationToMCPOp(op))
	}

	data := MCPToolData{
		SchemaPath:  schemaPath,
		ToolVarName: cmdName + "ToolGroup",
		ToolName:    "bitbucket_" + cmdUse,
		Description: buildToolDescription(cmdShort, mcpOps),
		Operations:  mcpOps,
	}

	tmpl, err := template.New("mcptools").Funcs(templateFuncMap).Parse(fileTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing template: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "executing template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "formatting generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated MCP tool %q with %d operations → %s\n", data.ToolName, len(data.Operations), outputPath)
}
