// Code generated by scripts/gen_commands/main.go DO NOT EDIT.
// Source: schema/hooks-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_commands/main.go schema/hooks-schema.yaml <output.go>

package commands

import (
"context"
"encoding/json"
"fmt"
"strconv"

"github.com/spf13/cobra"

"github.com/FabianSchurig/bitbucket-cli/internal/client"
"github.com/FabianSchurig/bitbucket-cli/internal/handlers"
"github.com/FabianSchurig/bitbucket-cli/internal/output"
)

// Ensure imports are used.
var (
_ = context.Background
_ = fmt.Errorf
_ = json.Marshal
_ = strconv.Itoa
_ = client.NewClient
_ = handlers.Dispatch
_ = output.Format
)

// NewHooksCommand returns the "hooks" cobra command with all sub-commands registered.
func NewHooksCommand() *cobra.Command {
cmd := &cobra.Command{
Use:   "hooks",
Short: `Manage Bitbucket webhooks`,
Long:  `Commands for listing, creating, updating, and deleting Bitbucket webhooks.`,
}

cmd.AddCommand(
newGetAWebhookResourceCmd(),
newListSubscribableWebhookTypesCmd(),
newListWebhooksForARepositoryCmd(),
newCreateAWebhookForARepositoryCmd(),
newGetAWebhookForARepositoryCmd(),
newUpdateAWebhookForARepositoryCmd(),
newDeleteAWebhookForARepositoryCmd(),
newListWebhooksForAWorkspaceCmd(),
newCreateAWebhookForAWorkspaceCmd(),
newGetAWebhookForAWorkspaceCmd(),
newUpdateAWebhookForAWorkspaceCmd(),
newDeleteAWebhookForAWorkspaceCmd(),
)

return cmd
}

// newGetAWebhookResourceCmd returns the "hooks get-awebhook-resource" cobra command.
// operationId: getAWebhookResource
func newGetAWebhookResourceCmd() *cobra.Command {
var (
)

cmd := &cobra.Command{
Use:   "get-awebhook-resource",
Short: `Get a webhook resource`,
Long:  "Returns the webhook resource or subject types on which webhooks can\nbe registered.\n\nEach resource/subject type contains an `events` link that returns the\npaginated list of specific events each individual subject type can\nemit.\n\nThis endpoint is publicly accessible and does not require\nauthentication or scopes.",
RunE: func(cmd *cobra.Command, args []string) error {
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/hook_events",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
return cmd
}

// newListSubscribableWebhookTypesCmd returns the "hooks list-subscribable-webhook-types" cobra command.
// operationId: listSubscribableWebhookTypes
func newListSubscribableWebhookTypesCmd() *cobra.Command {
var (
subjectType string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "list-subscribable-webhook-types",
Short: `List subscribable webhook types`,
Long:  "Returns a paginated list of all valid webhook events for the\nspecified entity.\n**The team and user webhooks are deprecated, and you should use workspace instead.\nFor more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\n\nThis is public data that does not require any scopes or authentication.\n\nNOTE: The example response is a truncated response object for the `workspace` `subject_type`.\nWe return the same structure for the other `subject_type` objects.",
RunE: func(cmd *cobra.Command, args []string) error {
if subjectType == "" {
return fmt.Errorf("--subject-type is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"subject_type": subjectType,
}
queryParams := map[string]string{
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/hook_events/{subject_type}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&subjectType, "subject-type", "", "subject_type (path parameter)")
cmd.Flags().IntVar(&page, "page", 0, "Page number (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "Number of items per page (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

// newListWebhooksForARepositoryCmd returns the "hooks list-webhooks-for-arepository" cobra command.
// operationId: listWebhooksForARepository
func newListWebhooksForARepositoryCmd() *cobra.Command {
var (
repoSlug string
workspace string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "list-webhooks-for-arepository",
Short: `List webhooks for a repository`,
Long:  `Returns a paginated list of webhooks installed on this repository.`,
RunE: func(cmd *cobra.Command, args []string) error {
if repoSlug == "" {
return fmt.Errorf("--repo-slug is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"repo_slug": repoSlug,
"workspace": workspace,
}
queryParams := map[string]string{
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/repositories/{workspace}/{repo_slug}/hooks",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&repoSlug, "repo-slug", "", "repo_slug (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
cmd.Flags().IntVar(&page, "page", 0, "Page number (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "Number of items per page (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

// newCreateAWebhookForARepositoryCmd returns the "hooks create-awebhook-for-arepository" cobra command.
// operationId: createAWebhookForARepository
func newCreateAWebhookForARepositoryCmd() *cobra.Command {
var (
repoSlug string
workspace string
)

cmd := &cobra.Command{
Use:   "create-awebhook-for-arepository",
Short: `Create a webhook for a repository`,
Long:  "Creates a new webhook on the specified repository.\n\nExample:\n\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo-slug/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to generate a HMAC\ndigest value sent in the `X-Hub-Signature` header at delivery time. Passing\na `null` or empty `secret` or not passing a `secret` will leave the webhook's\nsecret unset. Bitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nNote that this call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nAlso note that the `url` must properly resolve and cannot be an\ninternal, non-routed address.",
RunE: func(cmd *cobra.Command, args []string) error {
if repoSlug == "" {
return fmt.Errorf("--repo-slug is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"repo_slug": repoSlug,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "POST",
					URLTemplate: "/repositories/{workspace}/{repo_slug}/hooks",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&repoSlug, "repo-slug", "", "repo_slug (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newGetAWebhookForARepositoryCmd returns the "hooks get-awebhook-for-arepository" cobra command.
// operationId: getAWebhookForARepository
func newGetAWebhookForARepositoryCmd() *cobra.Command {
var (
repoSlug string
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "get-awebhook-for-arepository",
Short: `Get a webhook for a repository`,
Long:  `Returns the webhook with the specified id installed on the specified
repository.`,
RunE: func(cmd *cobra.Command, args []string) error {
if repoSlug == "" {
return fmt.Errorf("--repo-slug is required")
}
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"repo_slug": repoSlug,
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/repositories/{workspace}/{repo_slug}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&repoSlug, "repo-slug", "", "repo_slug (path parameter)")
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newUpdateAWebhookForARepositoryCmd returns the "hooks update-awebhook-for-arepository" cobra command.
// operationId: updateAWebhookForARepository
func newUpdateAWebhookForARepositoryCmd() *cobra.Command {
var (
repoSlug string
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "update-awebhook-for-arepository",
Short: `Update a webhook for a repository`,
Long:  "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest sent in the\n`X-Hub-Signature` header at delivery time. This signature is only generated\nwhen the hook has a secret.\n\nSet the hook's secret by passing the new value in the `secret` field. Passing a\n`null` value in the `secret` field will remove the secret from the hook. The\nhook's secret can be left unchanged by not passing the `secret` field in the\nrequest.",
RunE: func(cmd *cobra.Command, args []string) error {
if repoSlug == "" {
return fmt.Errorf("--repo-slug is required")
}
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"repo_slug": repoSlug,
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "PUT",
					URLTemplate: "/repositories/{workspace}/{repo_slug}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&repoSlug, "repo-slug", "", "repo_slug (path parameter)")
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newDeleteAWebhookForARepositoryCmd returns the "hooks delete-awebhook-for-arepository" cobra command.
// operationId: deleteAWebhookForARepository
func newDeleteAWebhookForARepositoryCmd() *cobra.Command {
var (
repoSlug string
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "delete-awebhook-for-arepository",
Short: `Delete a webhook for a repository`,
Long:  `Deletes the specified webhook subscription from the given
repository.`,
RunE: func(cmd *cobra.Command, args []string) error {
if repoSlug == "" {
return fmt.Errorf("--repo-slug is required")
}
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"repo_slug": repoSlug,
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "DELETE",
					URLTemplate: "/repositories/{workspace}/{repo_slug}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&repoSlug, "repo-slug", "", "repo_slug (path parameter)")
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newListWebhooksForAWorkspaceCmd returns the "hooks list-webhooks-for-aworkspace" cobra command.
// operationId: listWebhooksForAWorkspace
func newListWebhooksForAWorkspaceCmd() *cobra.Command {
var (
workspace string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "list-webhooks-for-aworkspace",
Short: `List webhooks for a workspace`,
Long:  `Returns a paginated list of webhooks installed on this workspace.`,
RunE: func(cmd *cobra.Command, args []string) error {
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"workspace": workspace,
}
queryParams := map[string]string{
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/workspaces/{workspace}/hooks",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
cmd.Flags().IntVar(&page, "page", 0, "Page number (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "Number of items per page (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

// newCreateAWebhookForAWorkspaceCmd returns the "hooks create-awebhook-for-aworkspace" cobra command.
// operationId: createAWebhookForAWorkspace
func newCreateAWebhookForAWorkspaceCmd() *cobra.Command {
var (
workspace string
)

cmd := &cobra.Command{
Use:   "create-awebhook-for-aworkspace",
Short: `Create a webhook for a workspace`,
Long:  "Creates a new webhook on the specified workspace.\n\nWorkspace webhooks are fired for events from all repositories contained\nby that workspace.\n\nExample:\n\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\n      \"events\": [\n        \"repo:push\",\n        \"issue:created\",\n        \"issue:updated\"\n      ]\n    }'\n```\n\nWhen the `secret` is provided it will be used as the key to generate a HMAC\ndigest value sent in the `X-Hub-Signature` header at delivery time. Passing\na `null` or empty `secret` or not passing a `secret` will leave the webhook's\nsecret unset. Bitbucket only generates the `X-Hub-Signature` when the webhook's\nsecret is set.\n\nThis call requires the webhook scope, as well as any scope\nthat applies to the events that the webhook subscribes to. In the\nexample above that means: `webhook`, `repository` and `issue`.\n\nThe `url` must properly resolve and cannot be an internal, non-routed address.\n\nOnly workspace owners can install webhooks on workspaces.",
RunE: func(cmd *cobra.Command, args []string) error {
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "POST",
					URLTemplate: "/workspaces/{workspace}/hooks",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newGetAWebhookForAWorkspaceCmd returns the "hooks get-awebhook-for-aworkspace" cobra command.
// operationId: getAWebhookForAWorkspace
func newGetAWebhookForAWorkspaceCmd() *cobra.Command {
var (
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "get-awebhook-for-aworkspace",
Short: `Get a webhook for a workspace`,
Long:  `Returns the webhook with the specified id installed on the given
workspace.`,
RunE: func(cmd *cobra.Command, args []string) error {
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/workspaces/{workspace}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newUpdateAWebhookForAWorkspaceCmd returns the "hooks update-awebhook-for-aworkspace" cobra command.
// operationId: updateAWebhookForAWorkspace
func newUpdateAWebhookForAWorkspaceCmd() *cobra.Command {
var (
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "update-awebhook-for-aworkspace",
Short: `Update a webhook for a workspace`,
Long:  "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest sent in the\n`X-Hub-Signature` header at delivery time. This signature is only generated\nwhen the hook has a secret.\n\nSet the hook's secret by passing the new value in the `secret` field. Passing a\n`null` value in the `secret` field will remove the secret from the hook. The\nhook's secret can be left unchanged by not passing the `secret` field in the\nrequest.",
RunE: func(cmd *cobra.Command, args []string) error {
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "PUT",
					URLTemplate: "/workspaces/{workspace}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

// newDeleteAWebhookForAWorkspaceCmd returns the "hooks delete-awebhook-for-aworkspace" cobra command.
// operationId: deleteAWebhookForAWorkspace
func newDeleteAWebhookForAWorkspaceCmd() *cobra.Command {
var (
uid string
workspace string
)

cmd := &cobra.Command{
Use:   "delete-awebhook-for-aworkspace",
Short: `Delete a webhook for a workspace`,
Long:  `Deletes the specified webhook subscription from the given workspace.`,
RunE: func(cmd *cobra.Command, args []string) error {
if uid == "" {
return fmt.Errorf("--uid is required")
}
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"uid": uid,
"workspace": workspace,
}
queryParams := map[string]string{
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "DELETE",
					URLTemplate: "/workspaces/{workspace}/hooks/{uid}",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         false,
				})
},
}
cmd.Flags().StringVar(&uid, "uid", "", "uid (path parameter)")
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
return cmd
}

