// Code generated by scripts/gen_commands/main.go DO NOT EDIT.
// Source: schema/search-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_commands/main.go schema/search-schema.yaml <output.go>

package commands

import (
"context"
"encoding/json"
"fmt"
"strconv"

"github.com/spf13/cobra"

"github.com/FabianSchurig/bitbucket-cli/internal/client"
"github.com/FabianSchurig/bitbucket-cli/internal/handlers"
"github.com/FabianSchurig/bitbucket-cli/internal/output"
)

// Ensure imports are used.
var (
_ = context.Background
_ = fmt.Errorf
_ = json.Marshal
_ = strconv.Itoa
_ = client.NewClient
_ = handlers.Dispatch
_ = output.Format
)

// NewSearchCommand returns the "search" cobra command with all sub-commands registered.
func NewSearchCommand() *cobra.Command {
cmd := &cobra.Command{
Use:   "search",
Short: `Search Bitbucket code`,
Long:  `Commands for searching code across Bitbucket repositories by user, workspace, or team.`,
}

cmd.AddCommand(
newSearchSearchTeamCmd(),
newSearchSearchAccountCmd(),
newSearchSearchWorkspaceCmd(),
)

return cmd
}

// newSearchSearchTeamCmd returns the "search search-team" cobra command.
// operationId: searchTeam
func newSearchSearchTeamCmd() *cobra.Command {
var (
username string
searchQuery string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "search-team",
Short: `Search for code in a team's repositories`,
Long:  "Search for code in the repositories of the specified team.\n\nNote that searches can match in the file's text (`content_matches`),\nthe path (`path_matches`), or both.\n\nYou can use the same syntax for the search query as in the UI.\nE.g. to search for \"foo\" only within the repository \"demo\",\nuse the query parameter `search_query=foo+repo:demo`.\n\nSimilar to other APIs, you can request more fields using a\n`fields` query parameter. E.g. to get some more information about\nthe repository of matched files, use the query parameter\n`search_query=foo&fields=%2Bvalues.file.commit.repository`\n(the `%2B` is a URL-encoded `+`).\n\nTry `fields=%2Bvalues.*.*.*.*` to get an idea what's possible.\n",
RunE: func(cmd *cobra.Command, args []string) error {
if username == "" {
return fmt.Errorf("--username is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"username": username,
}
queryParams := map[string]string{
"search_query": searchQuery,
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/teams/{username}/search/code",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&username, "username", "", "username (path parameter)")
cmd.Flags().StringVar(&searchQuery, "search-query", "", "search_query (query parameter)")
cmd.Flags().IntVar(&page, "page", 0, "page (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "pagelen (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

// newSearchSearchAccountCmd returns the "search search-account" cobra command.
// operationId: searchAccount
func newSearchSearchAccountCmd() *cobra.Command {
var (
selectedUser string
searchQuery string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "search-account",
Short: `Search for code in a user's repositories`,
Long:  "Search for code in the repositories of the specified user.\n\nNote that searches can match in the file's text (`content_matches`),\nthe path (`path_matches`), or both.\n\nYou can use the same syntax for the search query as in the UI.\nE.g. to search for \"foo\" only within the repository \"demo\",\nuse the query parameter `search_query=foo+repo:demo`.\n\nSimilar to other APIs, you can request more fields using a\n`fields` query parameter. E.g. to get some more information about\nthe repository of matched files, use the query parameter\n`search_query=foo&fields=%2Bvalues.file.commit.repository`\n(the `%2B` is a URL-encoded `+`).\n",
RunE: func(cmd *cobra.Command, args []string) error {
if selectedUser == "" {
return fmt.Errorf("--selected-user is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"selected_user": selectedUser,
}
queryParams := map[string]string{
"search_query": searchQuery,
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/users/{selected_user}/search/code",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&selectedUser, "selected-user", "", "selected_user (path parameter)")
cmd.Flags().StringVar(&searchQuery, "search-query", "", "search_query (query parameter)")
cmd.Flags().IntVar(&page, "page", 0, "page (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "pagelen (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

// newSearchSearchWorkspaceCmd returns the "search search-workspace" cobra command.
// operationId: searchWorkspace
func newSearchSearchWorkspaceCmd() *cobra.Command {
var (
workspace string
searchQuery string
page int
pagelen int
all bool
)

cmd := &cobra.Command{
Use:   "search-workspace",
Short: `Search for code in a workspace`,
Long:  "Search for code in the repositories of the specified workspace.\n\nNote that searches can match in the file's text (`content_matches`),\nthe path (`path_matches`), or both.\n\nYou can use the same syntax for the search query as in the UI.\nE.g. to search for \"foo\" only within the repository \"demo\",\nuse the query parameter `search_query=foo+repo:demo`.\n\nSimilar to other APIs, you can request more fields using a\n`fields` query parameter. E.g. to get some more information about\nthe repository of matched files, use the query parameter\n`search_query=foo&fields=%2Bvalues.file.commit.repository`\n(the `%2B` is a URL-encoded `+`).\n\nTry `fields=%2Bvalues.*.*.*.*` to get an idea what's possible.\n",
RunE: func(cmd *cobra.Command, args []string) error {
if workspace == "" {
return fmt.Errorf("--workspace is required")
}
c, err := client.NewClient()
if err != nil {
return err
}
pathParams := map[string]string{
"workspace": workspace,
}
queryParams := map[string]string{
"search_query": searchQuery,
"page": strconv.Itoa(page),
"pagelen": strconv.Itoa(pagelen),
}
body := ""
return handlers.Dispatch(context.Background(), c, handlers.Request{
					Method:      "GET",
					URLTemplate: "/workspaces/{workspace}/search/code",
					PathParams:  pathParams,
					QueryParams: queryParams,
					Body:        body,
					All:         all,
				})
},
}
cmd.Flags().StringVar(&workspace, "workspace", "", "workspace (path parameter)")
cmd.Flags().StringVar(&searchQuery, "search-query", "", "search_query (query parameter)")
cmd.Flags().IntVar(&page, "page", 0, "page (query parameter)")
cmd.Flags().IntVar(&pagelen, "pagelen", 0, "pagelen (query parameter)")
cmd.Flags().BoolVar(&all, "all", true, "Traverse all pages (follows 'next' cursor)")
return cmd
}

