// Code generated by scripts/gen_mcptools/main.go DO NOT EDIT.
// Source: schema/addon-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_mcptools/main.go schema/addon-schema.yaml <output.go>

package mcptools

// AddonToolGroup contains the MCP tool definition for the "bitbucket_addon" tool group.
var AddonToolGroup = ToolGroup{
	Name:        `bitbucket_addon`,
	Description: `Manage Bitbucket Connect addons

Available operations:
- updateAnInstalledApp: Update an installed app [PUT]
- deleteAnApp: Delete an app [DELETE]
- listLinkersForAnApp: List linkers for an app [GET]
- getALinkerForAnApp: Get a linker for an app [GET]
- listLinkerValuesForALinker: List linker values for a linker [GET]
- createALinkerValue: Create a linker value [POST]
- updateALinkerValue: Update a linker value [PUT]
- deleteAllLinkerValues: Delete all linker values [DELETE]
- getALinkerValue: Get a linker value [GET]
- deleteALinkerValue: Delete a linker value [DELETE]
`,
	Operations: []OperationDef{
		{
			OperationID: `updateAnInstalledApp`,
			Method:      `PUT`,
			Path:        `/addon`,
			Summary:     `Update an installed app`,
			Description: "Updates the application installation for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket need not use this endpoint as updates for those\napplications can be sent out via the UI of that section.\n\nPassing an empty body will update the installation using the\nexisting descriptor URL.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{}'\n```\n\nThe new `descriptor` for the installation can be also provided\nin the body directly.\n\n```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor\": $NEW_DESCRIPTOR}'\n```\n\nIn both these modes the URL of the descriptor cannot be changed. To\nchange the descriptor location and upgrade an installation\nthe request must be made exclusively with a `descriptor_url`.\n\n ```\n$ curl -X PUT https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\"descriptor_url\": $NEW_URL}'\n```\n\nThe `descriptor_url` must exactly match the marketplace registration\nthat Atlassian has for the application. Contact your Atlassian\ndeveloper advocate to update this registration. Once the registration\nhas been updated you may call this resource for each installation.\n\nNote that the scopes of the application cannot be increased\nin the new descriptor nor reduced to none.",
			Params: []ParamDef{
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `deleteAnApp`,
			Method:      `DELETE`,
			Path:        `/addon`,
			Summary:     `Delete an app`,
			Description: "Deletes the application for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/addon \\\n  -H \"Authorization: JWT <JWT Token>\"\n```",
			Params: []ParamDef{
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `listLinkersForAnApp`,
			Method:      `GET`,
			Path:        `/addon/linkers`,
			Summary:     `List linkers for an app`,
			Description: `Gets a list of all [linkers](/cloud/bitbucket/modules/linker/)
for the authenticated application.

This endpoint is deprecated and will be removed by May 2026.`,
			Params: []ParamDef{
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `getALinkerForAnApp`,
			Method:      `GET`,
			Path:        `/addon/linkers/{linker_key}`,
			Summary:     `Get a linker for an app`,
			Description: "Gets a [linker](/cloud/bitbucket/modules/linker/) specified by `linker_key`\nfor the authenticated application.\n\nThis endpoint is deprecated and will be removed by May 2026.",
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `listLinkerValuesForALinker`,
			Method:      `GET`,
			Path:        `/addon/linkers/{linker_key}/values`,
			Summary:     `List linker values for a linker`,
			Description: "Gets a list of all [linker](/cloud/bitbucket/modules/linker/) values for the\nspecified linker of the authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)\n\nThis endpoint is deprecated and will be removed by May 2026.",
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `createALinkerValue`,
			Method:      `POST`,
			Path:        `/addon/linkers/{linker_key}/values`,
			Summary:     `Create a linker value`,
			Description: "Creates a [linker](/cloud/bitbucket/modules/linker/) value for the specified\nlinker of authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)\n\nThis endpoint is deprecated and will be removed by May 2026.",
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `updateALinkerValue`,
			Method:      `PUT`,
			Path:        `/addon/linkers/{linker_key}/values`,
			Summary:     `Update a linker value`,
			Description: "Bulk update [linker](/cloud/bitbucket/modules/linker/) values for the specified\nlinker of the authenticated application.\n\nA linker value lets applications supply values to modify its regular expression.\n\nThe base regular expression must use a Bitbucket-specific match group `(?K)`\nwhich will be translated to `([\\w\\-]+)`. A value must match this pattern.\n\n[Read more about linker values](/cloud/bitbucket/modules/linker/#usingthebitbucketapitosupplyvalues)\n\nThis endpoint is deprecated and will be removed by May 2026.",
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `deleteAllLinkerValues`,
			Method:      `DELETE`,
			Path:        `/addon/linkers/{linker_key}/values`,
			Summary:     `Delete all linker values`,
			Description: `Delete all [linker](/cloud/bitbucket/modules/linker/) values for the
specified linker of the authenticated application.

This endpoint is deprecated and will be removed by May 2026.`,
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `getALinkerValue`,
			Method:      `GET`,
			Path:        `/addon/linkers/{linker_key}/values/{value_id}`,
			Summary:     `Get a linker value`,
			Description: `Get a single [linker](/cloud/bitbucket/modules/linker/) value
of the authenticated application.

This endpoint is deprecated and will be removed by May 2026.`,
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
				{Name: `value_id`, In: `path`, Type: `integer`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `deleteALinkerValue`,
			Method:      `DELETE`,
			Path:        `/addon/linkers/{linker_key}/values/{value_id}`,
			Summary:     `Delete a linker value`,
			Description: `Delete a single [linker](/cloud/bitbucket/modules/linker/) value
of the authenticated application.

This endpoint is deprecated and will be removed by May 2026.`,
			Params: []ParamDef{
				{Name: `linker_key`, In: `path`, Type: `string`, Required: true},
				{Name: `value_id`, In: `path`, Type: `integer`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
	},
}
