// Code generated by scripts/gen_mcptools/main.go DO NOT EDIT.
// Source: schema/downloads-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_mcptools/main.go schema/downloads-schema.yaml <output.go>

package mcptools

// DownloadsToolGroup contains the MCP tool definition for the "bitbucket_downloads" tool group.
var DownloadsToolGroup = ToolGroup{
	Name:        `bitbucket_downloads`,
	Description: `Manage Bitbucket repository downloads

Available operations:
- listDownloadArtifacts: List download artifacts [GET]
- uploadADownloadArtifact: Upload a download artifact [POST]
- getADownloadArtifactLink: Get a download artifact link [GET]
- deleteADownloadArtifact: Delete a download artifact [DELETE]
`,
	Operations: []OperationDef{
		{
			OperationID: `listDownloadArtifacts`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/downloads`,
			Summary:     `List download artifacts`,
			Description: `Returns a list of download links associated with the repository.`,
			Params: []ParamDef{
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `uploadADownloadArtifact`,
			Method:      `POST`,
			Path:        `/repositories/{workspace}/{repo_slug}/downloads`,
			Summary:     `Upload a download artifact`,
			Description: "Upload new download artifacts.\n\nTo upload files, perform a `multipart/form-data` POST containing one\nor more `files` fields:\n\n    $ echo Hello World > hello.txt\n    $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt\n\nWhen a file is uploaded with the same name as an existing artifact,\nthen the existing file will be replaced.",
			Params: []ParamDef{
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `getADownloadArtifactLink`,
			Method:      `GET`,
			Path:        `/repositories/{workspace}/{repo_slug}/downloads/{filename}`,
			Summary:     `Get a download artifact link`,
			Description: `Return a redirect to the contents of a download artifact.

This endpoint returns the actual file contents and not the artifact's
metadata.

    $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt
    Hello World`,
			Params: []ParamDef{
				{Name: `filename`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
		{
			OperationID: `deleteADownloadArtifact`,
			Method:      `DELETE`,
			Path:        `/repositories/{workspace}/{repo_slug}/downloads/{filename}`,
			Summary:     `Delete a download artifact`,
			Description: `Deletes the specified download artifact from the repository.`,
			Params: []ParamDef{
				{Name: `filename`, In: `path`, Type: `string`, Required: true},
				{Name: `repo_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{
			},
			HasBody:   false,
			Paginated: false,
		},
	},
}
