package tfprovider

// CRUDConfig maps each resource group to its primary CRUD operation IDs.
//
// This is a hand-written configuration that selects the "main" resource
// for each group from the many sub-resource endpoints generated by the
// OpenAPI schema. The mapping is intentionally explicit to avoid fragile
// heuristics.
//
// When new resource groups are added, add an entry here. If an operation
// ID doesn't exist in the generated code, it is silently ignored.
var CRUDConfig = map[string]CRUDMapping{
	"repos": {
		Create: "createARepository",
		Read:   "getARepository",
		Update: "updateARepository",
		Delete: "deleteARepository",
		List:   "listRepositoriesInAWorkspace",
	},
	"pr": {
		Create: "createAPullRequest",
		Read:   "getAPullRequest",
		Update: "updateAPullRequest",
		List:   "listPullRequests",
	},
	"projects": {
		Create: "createAProjectInAWorkspace",
		Read:   "getAProjectForAWorkspace",
		Update: "updateAProjectForAWorkspace",
		Delete: "deleteAProjectForAWorkspace",
		List:   "listProjectsInAWorkspace",
	},
	"workspaces": {
		Read: "getAWorkspace",
		List: "listWorkspacesForUser",
	},
	"issues": {
		Create: "createAnIssue",
		Read:   "getAnIssue",
		Update: "updateAnIssue",
		Delete: "deleteAnIssue",
		List:   "listIssues",
	},
	"hooks": {
		Create: "createAWebhookForARepository",
		Read:   "getAWebhookForARepository",
		Update: "updateAWebhookForARepository",
		Delete: "deleteAWebhookForARepository",
		List:   "listWebhooksForARepository",
	},
	"snippets": {
		Create: "createASnippet",
		Read:   "getASnippet",
		Update: "updateASnippet",
		Delete: "deleteASnippet",
		List:   "listSnippets",
	},
	"refs": {
		Create: "createABranch",
		Read:   "getABranch",
		Delete: "deleteABranch",
		List:   "listBranchesAndTags",
	},
	"commits": {
		Read: "getACommit",
		List: "listCommits",
	},
	"pipelines": {
		Create: "createPipelineForRepository",
		Read:   "getPipelineForRepository",
		List:   "getPipelinesForRepository",
	},
	"deployments": {
		Create: "createEnvironment",
		Read:   "getEnvironmentForRepository",
		Delete: "deleteEnvironmentForRepository",
		List:   "getEnvironmentsForRepository",
	},
	"branch-restrictions": {
		Create: "createABranchRestrictionRule",
		Read:   "getABranchRestrictionRule",
		Update: "updateABranchRestrictionRule",
		Delete: "deleteABranchRestrictionRule",
		List:   "listBranchRestrictions",
	},
	"branching-model": {
		Read:   "getTheBranchingModelForARepository",
		Update: "updateTheBranchingModelConfigForARepository",
	},
	"commit-statuses": {
		Create: "createABuildStatusForACommit",
		Read:   "getABuildStatusForACommit",
		Update: "updateABuildStatusForACommit",
		List:   "listCommitStatusesForACommit",
	},
	"downloads": {
		Create: "uploadADownloadArtifact",
		Read:   "getADownloadArtifactLink",
		Delete: "deleteADownloadArtifact",
		List:   "listDownloadArtifacts",
	},
	"users": {
		Read: "getAUser",
		List: "listSshKeys",
	},
	"reports": {
		Create: "createOrUpdateReport",
		Read:   "getReport",
		Delete: "deleteReport",
		List:   "getReportsForCommit",
	},
	"search": {
		List: "searchWorkspace",
	},
	"properties": {
		Read:   "getRepositoryHostedPropertyValue",
		Update: "updateRepositoryHostedPropertyValue",
		Delete: "deleteRepositoryHostedPropertyValue",
	},
	"addon": {
		Update: "updateAnInstalledApp",
		Delete: "deleteAnApp",
		List:   "listLinkersForAnApp",
	},
	// ─── Sub-resource CRUD mappings ───────────────────────────────────────────
	// These reference operations that live inside existing generated groups
	// and are registered as additional Terraform resources via sub_resources.go.
	"workspace-hooks": {
		Create: "createAWebhookForAWorkspace",
		Read:   "getAWebhookForAWorkspace",
		Update: "updateAWebhookForAWorkspace",
		Delete: "deleteAWebhookForAWorkspace",
		List:   "listWebhooksForAWorkspace",
	},
	"default-reviewers": {
		Read:   "getADefaultReviewer",
		Create: "addAUserToTheDefaultReviewers",
		Delete: "removeAUserFromTheDefaultReviewers",
		List:   "listDefaultReviewers",
	},
	"project-default-reviewers": {
		Read:   "getWorkspacesProjectsDefault-Reviewers",
		Create: "addTheSpecificUserAsADefaultReviewerForTheProject",
		Delete: "removeTheSpecificUserFromTheProjectsDefaultReviewers",
		List:   "listTheDefaultReviewersInAProject",
	},
	"pipeline-variables": {
		Create: "createRepositoryPipelineVariable",
		Read:   "getRepositoryPipelineVariable",
		Update: "updateRepositoryPipelineVariable",
		Delete: "deleteRepositoryPipelineVariable",
		List:   "getRepositoryPipelineVariables",
	},
	"workspace-pipeline-variables": {
		Create: "createPipelineVariableForWorkspace",
		Read:   "getPipelineVariableForWorkspace",
		Update: "updatePipelineVariableForWorkspace",
		Delete: "deletePipelineVariableForWorkspace",
		List:   "getPipelineVariablesForWorkspace",
	},
	"deployment-variables": {
		Create: "createDeploymentVariable",
		Read:   "getDeploymentVariables",
		Update: "updateDeploymentVariable",
		Delete: "deleteDeploymentVariable",
	},
	"repo-group-permissions": {
		Read:   "getAnExplicitGroupPermissionForARepository",
		Update: "updateAnExplicitGroupPermissionForARepository",
		Delete: "deleteAnExplicitGroupPermissionForARepository",
		List:   "listExplicitGroupPermissionsForARepository",
	},
	"repo-user-permissions": {
		Read:   "getAnExplicitUserPermissionForARepository",
		Update: "updateAnExplicitUserPermissionForARepository",
		Delete: "deleteAnExplicitUserPermissionForARepository",
		List:   "listExplicitUserPermissionsForARepository",
	},
	"project-group-permissions": {
		Read:   "getAnExplicitGroupPermissionForAProject",
		Update: "updateAnExplicitGroupPermissionForAProject",
		Delete: "deleteAnExplicitGroupPermissionForAProject",
		List:   "listExplicitGroupPermissionsForAProject",
	},
	"project-user-permissions": {
		Read:   "getAnExplicitUserPermissionForAProject",
		Update: "updateAnExplicitUserPermissionForAProject",
		Delete: "deleteAnExplicitUserPermissionForAProject",
		List:   "listExplicitUserPermissionsForAProject",
	},
	"repo-deploy-keys": {
		Create: "addARepositoryDeployKey",
		Read:   "getARepositoryDeployKey",
		Update: "updateARepositoryDeployKey",
		Delete: "deleteARepositoryDeployKey",
		List:   "listRepositoryDeployKeys",
	},
	"project-deploy-keys": {
		Create: "createAProjectDeployKey",
		Read:   "getAProjectDeployKey",
		Delete: "deleteADeployKeyFromAProject",
		List:   "listProjectDeployKeys",
	},
	// ─── Wave 2: additional sub-resource CRUD mappings ────────────────────────
	"tags": {
		Create: "createATag",
		Read:   "getATag",
		Delete: "deleteATag",
		List:   "listTags",
	},
	"pipeline-ssh-keys": {
		Read:   "getRepositoryPipelineSshKeyPair",
		Update: "updateRepositoryPipelineKeyPair",
		Delete: "deleteRepositoryPipelineKeyPair",
	},
	"pipeline-known-hosts": {
		Create: "createRepositoryPipelineKnownHost",
		Read:   "getRepositoryPipelineKnownHost",
		Update: "updateRepositoryPipelineKnownHost",
		Delete: "deleteRepositoryPipelineKnownHost",
		List:   "getRepositoryPipelineKnownHosts",
	},
	"pipeline-schedules": {
		Create: "createRepositoryPipelineSchedule",
		Read:   "getRepositoryPipelineSchedule",
		Update: "updateRepositoryPipelineSchedule",
		Delete: "deleteRepositoryPipelineSchedule",
		List:   "getRepositoryPipelineSchedules",
	},
	"pipeline-config": {
		Read:   "getRepositoryPipelineConfig",
		Update: "updateRepositoryPipelineConfig",
	},
	"ssh-keys": {
		Create: "addANewSshKey",
		Read:   "getASshKey",
		Update: "updateASshKey",
		Delete: "deleteASshKey",
		List:   "listSshKeys",
	},
	"current-user": {
		Read: "getCurrentUser",
	},
	"forked-repository": {
		Create: "forkARepository",
		List:   "listRepositoryForks",
	},
	"project-branching-model": {
		Read:   "getTheBranchingModelForAProject",
		Update: "updateTheBranchingModelConfigForAProject",
	},
	"pipeline-oidc": {
		Read: "getOIDCConfiguration",
	},
	"pipeline-oidc-keys": {
		Read: "getOIDCKeys",
	},
	"workspace-members": {
		Read: "getUserMembershipForAWorkspace",
		List: "listUsersInAWorkspace",
	},
	"annotations": {
		Create: "createOrUpdateAnnotation",
		Read:   "getAnnotation",
		Delete: "deleteAnnotation",
		List:   "getAnnotationsForReport",
	},
	"commit-file": {
		Create: "createACommitByUploadingAFile",
		Read:   "getFileOrDirectoryContents",
	},
	"pr-comments": {
		Create: "createACommentOnAPullRequest",
		Read:   "getACommentOnAPullRequest",
		Update: "updateACommentOnAPullRequest",
		Delete: "deleteACommentOnAPullRequest",
		List:   "listCommentsOnAPullRequest",
	},
	"issue-comments": {
		Create: "createACommentOnAnIssue",
		Read:   "getACommentOnAnIssue",
		Update: "updateACommentOnAnIssue",
		Delete: "deleteACommentOnAnIssue",
		List:   "listCommentsOnAnIssue",
	},
	// ─── Wave 3: DevSecOps-focused sub-resource CRUD mappings ────────────────
	"repo-runners": {
		Create: "createRepositoryRunner",
		Read:   "getRepositoryRunner",
		Update: "updateRepositoryRunner",
		Delete: "deleteRepositoryRunner",
		List:   "getRepositoryRunners",
	},
	"workspace-runners": {
		Create: "createWorkspaceRunner",
		Read:   "getWorkspaceRunner",
		Update: "updateWorkspaceRunner",
		Delete: "deleteWorkspaceRunner",
		List:   "getWorkspaceRunners",
	},
	"pipeline-caches": {
		Read:   "getRepositoryPipelineCacheContentURI",
		Delete: "deleteRepositoryPipelineCache",
		List:   "getRepositoryPipelineCaches",
	},
	"gpg-keys": {
		Create: "addANewGpgKey",
		Read:   "getAGpgKey",
		Delete: "deleteAGpgKey",
		List:   "listGpgKeys",
	},
	"user-emails": {
		Read: "getAnEmailAddressForCurrentUser",
		List: "listEmailAddressesForCurrentUser",
	},
	"hook-types": {
		Read: "getAWebhookResource",
		List: "listSubscribableWebhookTypes",
	},
	"workspace-permissions": {
		Read: "getUserPermissionOnAWorkspace",
		List: "listUserPermissionsInAWorkspace",
	},
	"repo-settings": {
		Read:   "retrieveTheInheritanceStateForRepositorySettings",
		Update: "setTheInheritanceStateForRepositorySettings",
	},
}

// CRUDMapping holds operation IDs for each CRUD slot.
// Empty strings mean the operation is not available.
type CRUDMapping struct {
	Create string
	Read   string
	Update string
	Delete string
	List   string
}
