// Code generated by scripts/gen_terraform/main.go DO NOT EDIT.
// Source: schema/projects-schema.yaml
//
// This file is regenerated whenever the schema changes in CI.
// Do not edit manually — run: go run scripts/gen_terraform/main.go schema/projects-schema.yaml <output.go>

package tfprovider

func init() {
	RegisterResourceGroup(ProjectsResourceGroup)
}

// ProjectsResourceGroup contains the Terraform resource definition for the "projects" resource group.
var ProjectsResourceGroup = ResourceGroup{
	TypeName: `projects`,
	Description: `Manage Bitbucket projects

Available operations:
- listProjectsInAWorkspace: List projects in a workspace [GET]
- createAProjectInAWorkspace: Create a project in a workspace [POST]
- getAProjectForAWorkspace: Get a project for a workspace [GET]
- updateAProjectForAWorkspace: Update a project for a workspace [PUT]
- deleteAProjectForAWorkspace: Delete a project for a workspace [DELETE]
- listTheDefaultReviewersInAProject: List the default reviewers in a project [GET]
- getWorkspacesProjectsDefault-Reviewers: Get a default reviewer [GET]
- addTheSpecificUserAsADefaultReviewerForTheProject: Add the specific user as a default reviewer for the project [PUT]
- removeTheSpecificUserFromTheProjectsDefaultReviewers: Remove the specific user from the project's default reviewers [DELETE]
- listExplicitGroupPermissionsForAProject: List explicit group permissions for a project [GET]
- getAnExplicitGroupPermissionForAProject: Get an explicit group permission for a project [GET]
- updateAnExplicitGroupPermissionForAProject: Update an explicit group permission for a project [PUT]
- deleteAnExplicitGroupPermissionForAProject: Delete an explicit group permission for a project [DELETE]
- listExplicitUserPermissionsForAProject: List explicit user permissions for a project [GET]
- getAnExplicitUserPermissionForAProject: Get an explicit user permission for a project [GET]
- updateAnExplicitUserPermissionForAProject: Update an explicit user permission for a project [PUT]
- deleteAnExplicitUserPermissionForAProject: Delete an explicit user permission for a project [DELETE]
`,
	Ops: MapCRUDOps(`projects`, []OperationDef{
		{
			OperationID: `listProjectsInAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects`,
			Summary:     `List projects in a workspace`,
			Description: `Returns the list of projects in this workspace.`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-projects-get`,
		},
		{
			OperationID: `createAProjectInAWorkspace`,
			Method:      `POST`,
			Path:        `/workspaces/{workspace}/projects`,
			Summary:     `Create a project in a workspace`,
			Description: "Creates a new project.\n\nNote that the avatar has to be embedded as either a data-url\nor a URL to an external image as shown in the examples below:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/...\"\n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type: application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n       https://api.bitbucket.org/2.0/workspaces/teams-in-space/projects/ | jq .\n{\n  // Serialized project document\n}\n```\n\nor even:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"http://i.imgur.com/72tRx4w.gif\"\n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type: application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n       https://api.bitbucket.org/2.0/workspaces/teams-in-space/projects/ | jq .\n{\n  // Serialized project document\n}\n```",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-post`,
		},
		{
			OperationID: `getAProjectForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Get a project for a workspace`,
			Description: `Returns the requested project.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-projects-project-key-get`,
		},
		{
			OperationID: `updateAProjectForAWorkspace`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Update a project for a workspace`,
			Description: "Since this endpoint can be used to both update and to create a\nproject, the request body depends on the intent.\n\n#### Creation\n\nSee the POST documentation for the project collection for an\nexample of the request body.\n\nNote: The `key` should not be specified in the body of request\n(since it is already present in the URL). The `name` is required,\neverything else is optional.\n\n#### Update\n\nSee the POST documentation for the project collection for an\nexample of the request body.\n\nNote: The key is not required in the body (since it is already in\nthe URL). The key may be specified in the body, if the intent is\nto change the key itself. In such a scenario, the location of the\nproject is changed and is returned in the `Location` header of the\nresponse.",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-put`,
		},
		{
			OperationID: `deleteAProjectForAWorkspace`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Delete a project for a workspace`,
			Description: "Deletes this project. This is an irreversible operation.\n\nYou cannot delete a project that still contains repositories.\nTo delete the project, [delete](/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-delete)\nor transfer the repositories first.\n\nExample:\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/workspaces/bbworkspace1/projects/PROJ\n```",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-delete`,
		},
		{
			OperationID: `listTheDefaultReviewersInAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers`,
			Summary:     `List the default reviewers in a project`,
			Description: `Return a list of all default reviewers for a project. This is a list of users that will be added as default
reviewers to pull requests for any repository within the project.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `reviewer_type`, Type: `string`, Desc: `reviewer_type`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:pullrequest:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-get`,
		},
		{
			OperationID: `getWorkspacesProjectsDefault-Reviewers`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Get a default reviewer`,
			Description: `Returns the specified default reviewer.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `account_id`, Type: `string`, Desc: `The user's Atlassian account ID.`},
				{Path: `account_status`, Type: `string`, Desc: `The status of the account. Currently the only possible value is "active", but more values may be added in the future.`},
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `display_name`, Type: `string`, Desc: `display_name`},
				{Path: `has_2fa_enabled`, Type: `bool`, Desc: `has_2fa_enabled`},
				{Path: `is_staff`, Type: `bool`, Desc: `is_staff`},
				{Path: `nickname`, Type: `string`, Desc: `Account name defined by the owner. Should be used instead of the "username" field. Note that "nickname" cannot be used in place of "username" in URLs and queries, as "nickname" is not guaranteed to be unique.`},
				{Path: `uuid`, Type: `string`, Desc: `uuid`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:pullrequest:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-get`,
		},
		{
			OperationID: `addTheSpecificUserAsADefaultReviewerForTheProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Add the specific user as a default reviewer for the project`,
			Description: "Adds the specified user to the project's list of default reviewers. The method is\nidempotent. Accepts an optional body containing the `uuid` of the user to be added.",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `account_id`, Type: `string`, Desc: `The user's Atlassian account ID.`},
				{Path: `account_status`, Type: `string`, Desc: `The status of the account. Currently the only possible value is "active", but more values may be added in the future.`},
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `display_name`, Type: `string`, Desc: `display_name`},
				{Path: `has_2fa_enabled`, Type: `bool`, Desc: `has_2fa_enabled`},
				{Path: `is_staff`, Type: `bool`, Desc: `is_staff`},
				{Path: `nickname`, Type: `string`, Desc: `Account name defined by the owner. Should be used instead of the "username" field. Note that "nickname" cannot be used in place of "username" in URLs and queries, as "nickname" is not guaranteed to be unique.`},
				{Path: `uuid`, Type: `string`, Desc: `uuid`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-put`,
		},
		{
			OperationID: `removeTheSpecificUserFromTheProjectsDefaultReviewers`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Remove the specific user from the project's default reviewers`,
			Description: "Removes a default reviewer from the project.\n\nExample:\n```\n$ curl https://api.bitbucket.org/2.0/.../default-reviewers/%7Bf0e0e8e9-66c1-4b85-a784-44a9eb9ef1a6%7D\n\nHTTP/1.1 204\n```",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-delete`,
		},
		{
			OperationID: `listExplicitGroupPermissionsForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups`,
			Summary:     `List explicit group permissions for a project`,
			Description: `Returns a paginated list of explicit group permissions for the given project.
This endpoint does not support BBQL features.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-get`,
		},
		{
			OperationID: `getAnExplicitGroupPermissionForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Get an explicit group permission for a project`,
			Description: "Returns the group permission for a given group and project.\n\nOnly users with admin permission for the project may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`\n* `none`",
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-get`,
		},
		{
			OperationID: `updateAnExplicitGroupPermissionForAProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Update an explicit group permission for a project`,
			Description: "Updates the group permission, or grants a new permission if one does not already exist.\n\nOnly users with admin permission for the project may access this resource.\n\nDue to security concerns, the JWT and OAuth authentication methods are unsupported.\nThis is to ensure integrations and add-ons are not allowed to change permissions.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`",
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`write:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-put`,
		},
		{
			OperationID: `deleteAnExplicitGroupPermissionForAProject`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Delete an explicit group permission for a project`,
			Description: `Deletes the project group permission between the requested project and group, if one exists.

Only users with admin permission for the project may access this resource.`,
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`delete:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-delete`,
		},
		{
			OperationID: `listExplicitUserPermissionsForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users`,
			Summary:     `List explicit user permissions for a project`,
			Description: `Returns a paginated list of explicit user permissions for the given project.
This endpoint does not support BBQL features.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-get`,
		},
		{
			OperationID: `getAnExplicitUserPermissionForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Get an explicit user permission for a project`,
			Description: "Returns the explicit user permission for a given user and project.\n\nOnly users with admin permission for the project may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`\n* `none`",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-get`,
		},
		{
			OperationID: `updateAnExplicitUserPermissionForAProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Update an explicit user permission for a project`,
			Description: "Updates the explicit user permission for a given user and project. The selected\nuser must be a member of the workspace, and cannot be the workspace owner.\n\nOnly users with admin permission for the project may access this resource.\n\nDue to security concerns, the JWT and OAuth authentication methods are unsupported.\nThis is to ensure integrations and add-ons are not allowed to change permissions.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`write:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-put`,
		},
		{
			OperationID: `deleteAnExplicitUserPermissionForAProject`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Delete an explicit user permission for a project`,
			Description: `Deletes the project user permission between the requested project and user, if one exists.

Only users with admin permission for the project may access this resource.

Due to security concerns, the JWT and OAuth authentication methods are unsupported.
This is to ensure integrations and add-ons are not allowed to change permissions.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`delete:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-delete`,
		},
	}),
	AllOps: []OperationDef{
		{
			OperationID: `listProjectsInAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects`,
			Summary:     `List projects in a workspace`,
			Description: `Returns the list of projects in this workspace.`,
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-projects-get`,
		},
		{
			OperationID: `createAProjectInAWorkspace`,
			Method:      `POST`,
			Path:        `/workspaces/{workspace}/projects`,
			Summary:     `Create a project in a workspace`,
			Description: "Creates a new project.\n\nNote that the avatar has to be embedded as either a data-url\nor a URL to an external image as shown in the examples below:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/...\"\n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type: application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n       https://api.bitbucket.org/2.0/workspaces/teams-in-space/projects/ | jq .\n{\n  // Serialized project document\n}\n```\n\nor even:\n\n```\n$ body=$(cat << EOF\n{\n    \"name\": \"Mars Project\",\n    \"key\": \"MARS\",\n    \"description\": \"Software for colonizing mars.\",\n    \"links\": {\n        \"avatar\": {\n            \"href\": \"http://i.imgur.com/72tRx4w.gif\"\n        }\n    },\n    \"is_private\": false\n}\nEOF\n)\n$ curl -H \"Content-Type: application/json\" \\\n       -X POST \\\n       -d \"$body\" \\\n       https://api.bitbucket.org/2.0/workspaces/teams-in-space/projects/ | jq .\n{\n  // Serialized project document\n}\n```",
			Params: []ParamDef{
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-post`,
		},
		{
			OperationID: `getAProjectForAWorkspace`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Get a project for a workspace`,
			Description: `Returns the requested project.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-projects-project-key-get`,
		},
		{
			OperationID: `updateAProjectForAWorkspace`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Update a project for a workspace`,
			Description: "Since this endpoint can be used to both update and to create a\nproject, the request body depends on the intent.\n\n#### Creation\n\nSee the POST documentation for the project collection for an\nexample of the request body.\n\nNote: The `key` should not be specified in the body of request\n(since it is already present in the URL). The `name` is required,\neverything else is optional.\n\n#### Update\n\nSee the POST documentation for the project collection for an\nexample of the request body.\n\nNote: The key is not required in the body (since it is already in\nthe URL). The key may be specified in the body, if the intent is\nto change the key itself. In such a scenario, the location of the\nproject is changed and is returned in the `Location` header of the\nresponse.",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `description`, Type: `string`, Desc: `description`},
				{Path: `has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `key`, Type: `string`, Desc: `The project's key.`},
				{Path: `name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `updated_on`, Type: `string`, Desc: `updated_on`},
				{Path: `uuid`, Type: `string`, Desc: `The project's immutable id.`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-put`,
		},
		{
			OperationID: `deleteAProjectForAWorkspace`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}`,
			Summary:     `Delete a project for a workspace`,
			Description: "Deletes this project. This is an irreversible operation.\n\nYou cannot delete a project that still contains repositories.\nTo delete the project, [delete](/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-delete)\nor transfer the repositories first.\n\nExample:\n```\n$ curl -X DELETE https://api.bitbucket.org/2.0/workspaces/bbworkspace1/projects/PROJ\n```",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-delete`,
		},
		{
			OperationID: `listTheDefaultReviewersInAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers`,
			Summary:     `List the default reviewers in a project`,
			Description: `Return a list of all default reviewers for a project. This is a list of users that will be added as default
reviewers to pull requests for any repository within the project.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `reviewer_type`, Type: `string`, Desc: `reviewer_type`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:pullrequest:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-get`,
		},
		{
			OperationID: `getWorkspacesProjectsDefault-Reviewers`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Get a default reviewer`,
			Description: `Returns the specified default reviewer.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `account_id`, Type: `string`, Desc: `The user's Atlassian account ID.`},
				{Path: `account_status`, Type: `string`, Desc: `The status of the account. Currently the only possible value is "active", but more values may be added in the future.`},
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `display_name`, Type: `string`, Desc: `display_name`},
				{Path: `has_2fa_enabled`, Type: `bool`, Desc: `has_2fa_enabled`},
				{Path: `is_staff`, Type: `bool`, Desc: `is_staff`},
				{Path: `nickname`, Type: `string`, Desc: `Account name defined by the owner. Should be used instead of the "username" field. Note that "nickname" cannot be used in place of "username" in URLs and queries, as "nickname" is not guaranteed to be unique.`},
				{Path: `uuid`, Type: `string`, Desc: `uuid`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:pullrequest:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-get`,
		},
		{
			OperationID: `addTheSpecificUserAsADefaultReviewerForTheProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Add the specific user as a default reviewer for the project`,
			Description: "Adds the specified user to the project's list of default reviewers. The method is\nidempotent. Accepts an optional body containing the `uuid` of the user to be added.",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `account_id`, Type: `string`, Desc: `The user's Atlassian account ID.`},
				{Path: `account_status`, Type: `string`, Desc: `The status of the account. Currently the only possible value is "active", but more values may be added in the future.`},
				{Path: `created_on`, Type: `string`, Desc: `created_on`},
				{Path: `display_name`, Type: `string`, Desc: `display_name`},
				{Path: `has_2fa_enabled`, Type: `bool`, Desc: `has_2fa_enabled`},
				{Path: `is_staff`, Type: `bool`, Desc: `is_staff`},
				{Path: `nickname`, Type: `string`, Desc: `Account name defined by the owner. Should be used instead of the "username" field. Note that "nickname" cannot be used in place of "username" in URLs and queries, as "nickname" is not guaranteed to be unique.`},
				{Path: `uuid`, Type: `string`, Desc: `uuid`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-put`,
		},
		{
			OperationID: `removeTheSpecificUserFromTheProjectsDefaultReviewers`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/default-reviewers/{selected_user}`,
			Summary:     `Remove the specific user from the project's default reviewers`,
			Description: "Removes a default reviewer from the project.\n\nExample:\n```\n$ curl https://api.bitbucket.org/2.0/.../default-reviewers/%7Bf0e0e8e9-66c1-4b85-a784-44a9eb9ef1a6%7D\n\nHTTP/1.1 204\n```",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-default-reviewers-selected-user-delete`,
		},
		{
			OperationID: `listExplicitGroupPermissionsForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups`,
			Summary:     `List explicit group permissions for a project`,
			Description: `Returns a paginated list of explicit group permissions for the given project.
This endpoint does not support BBQL features.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-get`,
		},
		{
			OperationID: `getAnExplicitGroupPermissionForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Get an explicit group permission for a project`,
			Description: "Returns the group permission for a given group and project.\n\nOnly users with admin permission for the project may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`\n* `none`",
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-get`,
		},
		{
			OperationID: `updateAnExplicitGroupPermissionForAProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Update an explicit group permission for a project`,
			Description: "Updates the group permission, or grants a new permission if one does not already exist.\n\nOnly users with admin permission for the project may access this resource.\n\nDue to security concerns, the JWT and OAuth authentication methods are unsupported.\nThis is to ensure integrations and add-ons are not allowed to change permissions.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`",
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `group.full_slug`, Type: `string`, Desc: "The concatenation of the workspace's slug and the group's slug,\nseparated with a colon (e.g. `acme:developers`)\n"},
				{Path: `group.name`, Type: `string`, Desc: `group.name`},
				{Path: `group.slug`, Type: `string`, Desc: `The "sluggified" version of the group's name. This contains only ASCII
characters and can therefore be slightly different than the name`},
				{Path: `group.workspace.created_on`, Type: `string`, Desc: `group.workspace.created_on`},
				{Path: `group.workspace.forking_mode`, Type: `string`, Desc: `Controls the rules for forking repositories within this workspace.

* **allow_forks**: unrestricted forking
* **internal_only**: prevents forking of private repositories outside the workspace or to public repositories
 [allow_forks, internal_only]`},
				{Path: `group.workspace.is_privacy_enforced`, Type: `bool`, Desc: `Indicates whether the workspace enforces private content, or whether it allows public content.`},
				{Path: `group.workspace.is_private`, Type: `bool`, Desc: `Indicates whether the workspace is publicly accessible, or whether it is
private to the members and consequently only visible to members.`},
				{Path: `group.workspace.name`, Type: `string`, Desc: `The name of the workspace.`},
				{Path: `group.workspace.slug`, Type: `string`, Desc: `The short label that identifies this workspace.`},
				{Path: `group.workspace.updated_on`, Type: `string`, Desc: `group.workspace.updated_on`},
				{Path: `group.workspace.uuid`, Type: `string`, Desc: `The workspace's immutable id.`},
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`write:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-put`,
		},
		{
			OperationID: `deleteAnExplicitGroupPermissionForAProject`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/groups/{group_slug}`,
			Summary:     `Delete an explicit group permission for a project`,
			Description: `Deletes the project group permission between the requested project and group, if one exists.

Only users with admin permission for the project may access this resource.`,
			Params: []ParamDef{
				{Name: `group_slug`, In: `path`, Type: `string`, Required: true},
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`delete:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-groups-group-slug-delete`,
		},
		{
			OperationID: `listExplicitUserPermissionsForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users`,
			Summary:     `List explicit user permissions for a project`,
			Description: `Returns a paginated list of explicit user permissions for the given project.
This endpoint does not support BBQL features.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
				{Name: `page`, In: `query`, Type: `integer`, Required: false},
				{Name: `pagelen`, In: `query`, Type: `integer`, Required: false},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: true,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-get`,
		},
		{
			OperationID: `getAnExplicitUserPermissionForAProject`,
			Method:      `GET`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Get an explicit user permission for a project`,
			Description: "Returns the explicit user permission for a given user and project.\n\nOnly users with admin permission for the project may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`\n* `none`",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   false,
			Paginated: false,
			Scopes: []string{
				`read:project:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-get`,
		},
		{
			OperationID: `updateAnExplicitUserPermissionForAProject`,
			Method:      `PUT`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Update an explicit user permission for a project`,
			Description: "Updates the explicit user permission for a given user and project. The selected\nuser must be a member of the workspace, and cannot be the workspace owner.\n\nOnly users with admin permission for the project may access this resource.\n\nDue to security concerns, the JWT and OAuth authentication methods are unsupported.\nThis is to ensure integrations and add-ons are not allowed to change permissions.\n\nPermissions can be:\n\n* `admin`\n* `create-repo`\n* `write`\n* `read`",
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields: []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{
				{Path: `permission`, Type: `string`, Desc: `[read, write, create-repo, admin, none]`},
				{Path: `project.created_on`, Type: `string`, Desc: `project.created_on`},
				{Path: `project.description`, Type: `string`, Desc: `project.description`},
				{Path: `project.has_publicly_visible_repos`, Type: `bool`, Desc: `
Indicates whether the project contains publicly visible repositories.
Note that private projects cannot contain public repositories.`},
				{Path: `project.is_private`, Type: `bool`, Desc: `
Indicates whether the project is publicly accessible, or whether it is
private to the team and consequently only visible to team members.
Note that private projects cannot contain public repositories.`},
				{Path: `project.key`, Type: `string`, Desc: `The project's key.`},
				{Path: `project.name`, Type: `string`, Desc: `The name of the project.`},
				{Path: `project.updated_on`, Type: `string`, Desc: `project.updated_on`},
				{Path: `project.uuid`, Type: `string`, Desc: `The project's immutable id.`},
				{Path: `type`, Type: `string`, Desc: `type`},
			},
			HasBody:   true,
			Paginated: false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`write:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-put`,
		},
		{
			OperationID: `deleteAnExplicitUserPermissionForAProject`,
			Method:      `DELETE`,
			Path:        `/workspaces/{workspace}/projects/{project_key}/permissions-config/users/{selected_user_id}`,
			Summary:     `Delete an explicit user permission for a project`,
			Description: `Deletes the project user permission between the requested project and user, if one exists.

Only users with admin permission for the project may access this resource.

Due to security concerns, the JWT and OAuth authentication methods are unsupported.
This is to ensure integrations and add-ons are not allowed to change permissions.`,
			Params: []ParamDef{
				{Name: `project_key`, In: `path`, Type: `string`, Required: true},
				{Name: `selected_user_id`, In: `path`, Type: `string`, Required: true},
				{Name: `workspace`, In: `path`, Type: `string`, Required: true},
			},
			BodyFields:     []BodyFieldDef{},
			ResponseFields: []BodyFieldDef{},
			HasBody:        false,
			Paginated:      false,
			Scopes: []string{
				`admin:project:bitbucket`,
				`delete:permission:bitbucket`,
			},
			DocURL: `https://developer.atlassian.com/cloud/bitbucket/rest/api-group-projects/#api-workspaces-workspace-projects-project-key-permissions-config-users-selected-user-id-delete`,
		},
	},
}
